config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about', as: 'about'
  resources :games do
    resources :game_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    post "search" => "users#search"
  end
  resources :chats, only: %i[show create]
  resources :groups do
    get 'join' => 'groups#join'
    delete 'exit' => 'groups#exit'
    get 'group_mails/new'
    post 'group_mails/create'
  end
  get '/search', to: 'games#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, length: { in: 1..140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
  validates_uniqueness_of :game_id, scope: :user_id
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :game_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  validates :game_name, presence: true
  validates :caption, presence: true, length: { maximum: 300 }
  validates :star, presence: true
  validates :tag, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  scope :created_day_before, ->(d) { where(created_at: d.day.ago.all_day) }
end

app/models/game_comment.rb
class GameComment < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :comment, presence: true
end

app/models/group.rb
class Group < ApplicationRecord

  has_one_attached :image

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user

  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'

  has_many :group_mails, dependent: :destroy
  validates :name, presence: true
  validates :introduction, presence: true
end

app/models/group_mail.rb
class GroupMail < ApplicationRecord
  belongs_to :group
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy
  has_many :game_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followed # フォローの一覧画面でフォロワーを見れるように

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_many :view_counts, dependent: :destroy

  has_many :group_users
  has_many :groups, through: :group_users, source: :group

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 10 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_user_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :reject_non_related, only: [:show]

  def show
    @user = User.find(params[:id]) # チャットする相手は誰？
    rooms = current_user.user_rooms.pluck(:room_id) # ログイン中のユーザーの部屋情報を全て取得
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms) # その中にチャットする相手とのルームがあるか確認

    if user_rooms.nil? # ユーザールームが無かった場合
      @room = Room.new # 新しくRoomを作る
      @room.save # そして保存
      UserRoom.create(user_id: current_user.id, room_id: @room.id) # 自分の中間テーブルを作成
      UserRoom.create(user_id: @user.id, room_id: @room.id) # 相手の中間テーブルを作成
    else # ユーザールームがある場合
      @room = user_rooms.room # 変数@roomにユーザー（自分と相手）と紐づいているroomを代入
    end
    @chats = @room.chats # チャットの一覧
    @chat = Chat.new(room_id: @room.id) # チャットの投稿
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @room = @chat.room
    @chats = @room.chats
    render :validator unless @chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def reject_non_related
    user = User.find(params[:id])
    return if current_user.following?(user) && user.following?(current_user)

    redirect_to games_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_owner, only: %i[edit update,destroy]
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner = current_user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def index
    @game = Game.new
    @groups = Group.all
  end

  def show
    @game = Game.new
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to  group_path(@group)
  end

  def exit
    @group = Group.find(params[:group_id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to groups_path
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end


  def ensure_correct_owner
    @group = Group.find(params[:id])
    redirect_to groups_path unless @group.owner == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/group_mails_helper.rb
module GroupMailsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.file_field :image, class: "form-control-file", accept: 'image/*' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/groups/_index.html.erb
<div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>人数</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% groups.each do |group| %>
            <tr>
              <td>
                <% if group.image.attached? %>
                  <%= image_tag group.image, size: "100x100" %>
                <% else %>
                  <%= image_tag 'no_image', size: "100x100" %>
                <% end %>
              </td>
              <td><%= link_to group.name, group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.users.count %></td>
              <td>
                <% if group.owner == current_user %>
                  <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

app/views/groups/edit.html.erb
<div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <%= render 'layouts/errors', obj: @group %>
    <h3>Editing Group</h3>
      <%= render 'form', group: @group %>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
      <%= render 'users/user_info', user: current_user %>
      <%= render 'index', groups: @groups%>
  </div>
</div>

app/views/groups/new.html.erb
<div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <%= render 'layouts/errors', obj: @group %>
    <h3>Create Group</h3>
      <%= render 'form', group: @group %>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @game %>
  <div class='row'>
    <%= render 'users/user_info', user: current_user %>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <div>
        <% if @group.image.attached? %>
          <%= image_tag @group.image, size: "100x100" %>
        <% else %>
          <%= image_tag 'no_image', size: "100x100" %>
        <% end %><br>
        グループ名：<%= @group.name %><br>
        オーナー：<%= image_tag @group.owner.get_profile_image(100,100), class: 'placeholder-image', style: 'width: 100px; height: 100px;' %><%= @group.owner.name %>
      </div>
      <div>紹介文：<%= @group.introduction %></div>
      <% if @group.owner == current_user %>
        <%= link_to 'Notice an Event',group_group_mails_new_path(@group), class: "btn btn-sm btn-info" %>
        <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success edit_game_#{@group.id}" %>
        <%= link_to 'Destroy', group_path(@group),method: :delete,data: {confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger edit_game_#{@group.id}" %>
      <% elsif @group.users.include?(current_user) %>
        <%= link_to 'Leave this group', group_exit_path(@group), method: :delete, class: "btn btn-sm btn-danger" %>
      <% else %>
        <%= link_to 'Join this group', group_join_path(@group), class: "btn btn-sm btn-success" %>
      <% end %>
      <div>
        メンバー<br>
        <% @group.users.each do |member| %>
        <%= image_tag member.get_profile_image(100,100), class: 'placeholder-image', style: 'width: 100px; height: 100px;' %>
          <%= member.name %><br>
        <% end %>
      </div>
    </div>
  </div>
</div>