config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about', as: 'about'
  resources :games do
    resources :game_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    post "search" => "users#search"
  end
  resources :chats, only: %i[show create]
  resources :groups do
    get 'join' => 'groups#join'
    delete 'exit' => 'groups#exit'
    get 'group_mails/new'
    post 'group_mails/create'
  end
  get '/search', to: 'games#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, length: { in: 1..140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
  validates_uniqueness_of :game_id, scope: :user_id
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :game_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  validates :game_name, presence: true
  validates :caption, presence: true, length: { maximum: 300 }
  validates :star, presence: true
  validates :tag, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  scope :created_day_before, ->(d) { where(created_at: d.day.ago.all_day) }
end

app/models/game_comment.rb
class GameComment < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :comment, presence: true
end

app/models/group.rb
class Group < ApplicationRecord

  has_one_attached :image

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user

  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'

  has_many :group_mails, dependent: :destroy
  validates :name, presence: true
  validates :introduction, presence: true
end

app/models/group_mail.rb
class GroupMail < ApplicationRecord
  belongs_to :group
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy
  has_many :game_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followed # フォローの一覧画面でフォロワーを見れるように

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_many :view_counts, dependent: :destroy

  has_many :group_users
  has_many :groups, through: :group_users, source: :group

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 10 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_user_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :reject_non_related, only: [:show]

  def show
    @user = User.find(params[:id]) # チャットする相手は誰？
    rooms = current_user.user_rooms.pluck(:room_id) # ログイン中のユーザーの部屋情報を全て取得
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms) # その中にチャットする相手とのルームがあるか確認

    if user_rooms.nil? # ユーザールームが無かった場合
      @room = Room.new # 新しくRoomを作る
      @room.save # そして保存
      UserRoom.create(user_id: current_user.id, room_id: @room.id) # 自分の中間テーブルを作成
      UserRoom.create(user_id: @user.id, room_id: @room.id) # 相手の中間テーブルを作成
    else # ユーザールームがある場合
      @room = user_rooms.room # 変数@roomにユーザー（自分と相手）と紐づいているroomを代入
    end
    @chats = @room.chats # チャットの一覧
    @chat = Chat.new(room_id: @room.id) # チャットの投稿
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @room = @chat.room
    @chats = @room.chats
    render :validator unless @chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def reject_non_related
    user = User.find(params[:id])
    return if current_user.following?(user) && user.following?(current_user)

    redirect_to games_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: %i[edit update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @games = @user.games
    @today_games = @games.created_today
    @yesterday_games = @games.created_yesterday
    @this_week_games = @games.created_this_week
    @last_week_games = @games.created_last_week
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = 'You have updated user successfully.'
    else
      render 'edit'
    end
  end

  def search
    @user = User.find(params[:user_id])
    @games = @user.games
    @game = Game.new
    if params[:created_at] == ''
      @search_game = '日付を選択してください'
    else
      create_at = params[:created_at]
      @search_game = @games.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    return if @user == current_user

    redirect_to user_path(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/group_mails_helper.rb
module GroupMailsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(80,80), class: 'placeholder-image', style: 'width: 80px; height: 80px;' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= render "relationships/btn", user: user %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_search.html.erb
<h2>検索結果</h2>
<table>
  <th>投稿数</th>
  <td><%= search_game %></td>
</table>

app/views/users/_user_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100), class: 'placeholder-image', style: 'width: 100px; height: 100px;' %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <td><%= link_to user.followings.count, user_followings_path(user) %></td>
      </tr>
      <tr>
        <th>followers</th>
        <td><%= link_to user.followers.count, user_followers_path(user) %></td>
      </tr>
    </tbody>
  </table>
  <div class='row d-flex justify-content-center mb-3'>
    <% if current_user != user %>
      <%= render "relationships/btn", user: user %>
    <% end %>
    <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
      <%= link_to 'チャットを始める', chat_path(user.id), class: "ml-3" %>
    <% end %>
  </div>
  <div class="row">
    <% if current_user == user %>
        <%= link_to  edit_user_path(user.id), class: "btn btn-outline-secondary btn-block edit_user_path"  do %>
          <i class='fas fa-user-cog'></i>
        <% end %>
    <% end %>
  </div>
  <div><%= link_to "投稿", new_game_path,class: "btn btn-info btn-sm btn-block mb-3 mt-3" %></div>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
      <%= render 'user_info', user: current_user %>
    <div class='col-md-8 offset-md-1'>
    <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('.search_result').html("<%= j(render 'users/search',  search_game: @search_game ) %>")

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'user_info', user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Games</h2>
      <%= render 'games/index', games: @games %>
      <div>
        <%= form_with url: user_search_path(@user), method: :post, local: false do |f| %>
          <%= f.date_field :created_at %>
          <%= f.submit '検索', class: 'btn btn-primary'  %>
        <% end %>
        <div class="search_result">
          <% if @search_game.present? %>
            <%= render 'search', search_game: @search_game %>
          <% end %>
        </div>
      </div>
      <h2>投稿数の前日比・前週比</h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>昨日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @today_games.count %></td>
              <td><%= @yesterday_games.count %></td>
              <td>
                <% if @yesterday_games.count != 0 %>
                  <% day_rate = @today_games.count / @yesterday_games.count.to_f %>
                  <%= (day_rate * 100).round %>%
                <% else %>
                  -
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今週の投稿数</th>
              <th>先週の投稿数</th>
              <th>前週比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @this_week_games.count %></td>
              <td><%= @last_week_games.count %></td>
              <td>
                <% if @last_week_games.count != 0 %>
                  <% week_rate = @this_week_games.count / @last_week_games.count.to_f %>
                  <%= (week_rate * 100).round %>%
                <% else %>
                  -
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <canvas id="myChart"></canvas>
      <script src="//cdn.jsdelivr.net/npm/chart.js"></script>
    </div>
  </div>
</div>
<script>
  var ctx = document.getElementById('myChart');
  var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: [
          <% for i in 0..5 %>
            '<%= 6-i %>日前',
          <% end %>
              '今日'
          ],
      datasets: [{
          label: '投稿した記事の数',
          data: [
            <% for i in 0..6 %>
              <%= @games.created_day_before(6-i).count %>,
            <% end %>
          ],
          borderWidth: 1
      }]
      },
      options: {
        scales: {
          y:{
            min: 0,
            max: 10,
            ticks: {
              stepSize: 1
            }
          }
        }
      }
    });
</script>