config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about', as: 'about'
  resources :games do
    resources :game_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    post "search" => "users#search"
  end
  resources :chats, only: %i[show create]
  resources :groups do
    get 'join' => 'groups#join'
    delete 'exit' => 'groups#exit'
    get 'group_mails/new'
    post 'group_mails/create'
  end
  get '/search', to: 'games#search'
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :game_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  validates :game_name, presence: true
  validates :caption, presence: true, length: { maximum: 300 }
  validates :star, presence: true
  validates :tag, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  scope :created_day_before, ->(d) { where(created_at: d.day.ago.all_day) }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: %i[edit update destroy]

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id
    if @game.save
      redirect_to game_path(@game.id)
      flash[:notice] = 'You have created game successfully.'
    else
      @games = Game.all
      render :new
    end
  end

  def index
    @games = Game.all
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    if params[:sort] == 'newer'
      @games = Game.order(created_at: 'DESC')
    elsif params[:sort] == 'higher'
      @games = Game.order(star: 'DESC')
    elsif params[:sort] == 'liker'
      @games = Game.includes(:favorites).sort_by { |x| x.favorites.where(created_at: from...to).size }.reverse
    else
      @games = Game.all
    end
  end

  def show
    @game = Game.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, game_id: @game.id)
      current_user.view_counts.create(game_id: @game.id)
    end
    @game_comment = GameComment.new
  end

  def edit
    @game = Game.find(params[:id])
    if @game.user == current_user
      @game = Game.find(params[:id])
      render action: :edit
    else
      redirect_to :edit
    end
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to game_path(@game.id)
      flash[:notice] = 'You have updated game successfully.'
    else
      render :edit
    end
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end

  def search
    @tag = params[:tag]
    if @tag.present?
      @games = Game.where("tag LIKE?","%#{@tag}%")
    else
      @games = Game.all
    end
    render :search_result
  end

  private

  def game_params
    params.require(:game).permit(:game_name, :image, :tag, :caption,:star)
  end

  def ensure_correct_user
    @game = Game.find(params[:id])
    return if @game.user == current_user

    redirect_to games_path
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with model: game do |f| %>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, accept: "image/*"%>
  </div>
  <div class="form-group">
    <%= f.label :game_name %>
    <%= f.text_field :game_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_area :caption, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :Tag %>
    <%= f.text_field :tag, class: 'form-control' %>
  </div>
  <% if game.id.nil? %>
    <div class="form-group", id='star'>
      <%= f.label :Star %>
      <%= f.hidden_field :star, id: :review_star %>
    </div>
  <% else %>
    <%= render "output_star", game: game %>
  <% end %>
  <div class="form-group">
    <%= f.submit class: 'form-control' %>
  </div>
<% end %>

<script>
  raty(document.getElementById('star'), {
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      scoreName: 'game[star]'
  });
</script>

app/views/games/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Game_image</th>
      <th>Title</th>
      <th>tag</th>
      <th>like</th>
      <th>comments</th>
      <th>star</th>
    </tr>
  </thead>
  <tbody>
    <% games.each do |game| %>
      <tr>
        <td>
          <%= link_to user_path(game.user.id) do %>
            <%= image_tag game.user.get_profile_image(80,80), class: 'placeholder-image mt-3 rounded-circle', style: 'width: 100px; height: 100px;' %>
          <% end %>
        </td>
        <td> <%= image_tag game.get_image(100,80), class: 'placeholder-image mt-3', style: 'width: 100px; height: 80px;' %></td>
        <td><%= link_to game.game_name, game_path(game.id) %></td>
        <td><%= link_to game.tag, search_path(tag: game.tag) %></td>
        <td class=<%= "favorite-" + game.id.to_s %> >
            <%= render "favorites/btn", game: game %>
        </td>
        <td><%= render "game_comments/counter", game: game %></td>
        <td><%= render "games/output_star", game: game %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/_output_star.html.erb
<div id="star-<%= game.id %>"></div>
<script>
$('#star-<%= game.id %>').empty();
    var elem = document.querySelector('#star-<%= game.id %>');
    var opt = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        readOnly: true,
        score: <%= game.star %>
    };
    raty(elem,opt);
</script>

app/views/games/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-6'>
      <h1>編集フォーム</h1>
      <%= render 'layouts/errors', obj: @game %>
      <%= render 'form', game: @game %>
      <%= link_to "Show", game_path(@game.id) %> |
      <%= link_to "Back", games_path %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render '/users/user_info', user: current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Games</h2>
      <%= link_to '新しい順', games_path(sort: 'newer') %>｜<%= link_to '評価の高い順', games_path(sort: 'higher') %>｜<%= link_to '最近のいいね順', games_path(sort: 'liker') %>
      <%= render 'index', games: @games %>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-6'>
      <h1>投稿フォーム</h1>
      <%= render 'layouts/errors', obj: @game %>
      <%= render 'form', game: @game %>
    </div>
  </div>
</div>

app/views/games/search_result.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col'>
      <h2>Games search for "<%= @tag %>"</h2>
      <%= render 'index', games: @games%>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="container">
  <div class="row">
    <%= render '/users/user_info', user: @game.user %>
    
    <div class="col-md-8 offset-md-1">
      <!-- Game Detail -->
      <h2>Game Detail</h2>
      
      <!-- Contributor Section -->
      <h4>Contributor</h4>
      <%= link_to user_path(@game.user.id) do %>
        <%= image_tag @game.user.get_profile_image(100, 100), class: 'placeholder-image', style: 'width: 100px; height: 100px;' %>
        <%= @game.user.name %><br>
      <% end %>
      
      Post Date:<%= @game.created_at.strftime('%Y/%m/%d') %>
      
      <!-- Title -->
      <h4>Title</h4>
      <h5><%= @game.game_name %></h5>
      
      <!-- Edit and Destroy Buttons (if the user is the owner) -->
      <% if @game.user == current_user %>
        <%= link_to "Edit", edit_game_path(@game.id), class: "btn btn-sm btn-success" %>
        <%= link_to "Destroy", game_path(@game.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger destroy" %>
      <% end %>
      
      <!-- Table Section -->
      <h4>Game Statistics</h4>
      <table class="table">
        <thead>
          <th>Tag</th>
          <th>Like</th>
          <th>Views</th>
          <th>Comments</th>
          <th>Star</th>
        </thead>
        <tbody>
          <tr>
            <td><%= link_to @game.tag, search_path(tag: @game.tag) %></td>
            <td>
              <div class=<%= "favorite-" + @game.id.to_s %> >
                <%= render "favorites/btn", game: @game %>
              </div>
            </td>
            <td><%= @game.view_counts.count %></td>
            <td>
              <div class="game-comments-counter">
                <%= render "game_comments/counter", game: @game %>
              </div>
            </td>
            <td><%= render "output_star", game: @game %></td>
          </tr>
        </tbody>
      </table>
      
      <!-- Caption Section -->
      <h4>Caption</h4>
      <%= image_tag @game.get_image(400, 200), class: 'placeholder-image', style: 'width: 400px; height: 200px;' %><br>
      <%= @game.caption %>
      
      <!-- Game Comments Section -->
      <div class="game-comments-index">
        <%= render "game_comments/index", game: @game %>
      </div>
      
      <!-- Game Comments Form -->
      <h4>Comments</h4>
      <%= render "game_comments/form", game: @game, game_comment: @game_comment %>
    </div>
  </div>
</div>